services:
  app:
    image: ghcr.io/onkr0d/titanic/titanic:v1.4.5@sha256:523cdfcaaf41546952b3fefde28862bc930d4dd776ac2917f56f399cbe127a42
    user: "0:0"
    restart: unless-stopped
    ports:
      - "${APP_TITANIC_PORT:-3029}:3029"
    environment:
      - RUST_LOG=info
      - IS_DEV=false
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID:-titanic-uploader}
      - PLEX_MEDIA_PATH=${PLEX_MEDIA_PATH:-/downloads}
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ${UMBREL_ROOT}/home/Downloads:/downloads
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3029/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
